In [1]:
import numpy as np

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

In [13]:

arr1 = np.array([1,2,3,6,4,5])
rev_arr = arr1[::-1]
print(rev_arr)


[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
True
[0 5 7 8 9]
[0 1 2]
45
[[14]
 [16]
 [15]]
[[20  9 16]]
176 [98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]] [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]] 137180.0000000001
[[16 19]
 [26 31]] [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]


(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two
NumPy in-built methods

In [ ]:

arr2 = np.array([[1,2,3],[2,4,5],[1,2,3]])
flat_arr = arr2.flatten()
print(flat_arr)

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

In [34]:

a = np.array([[1,2],[3,4]])
b = np.array([[1,2],[3,4]])
comp = np.array_equal(a,b)
print(comp)

True


(d) Find the most frequent value and their indice(s) in the following arrays:
i.
x = np.array([1,2,3,4,5,1,2,1,1,1])
ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:

x = np.array([1,2,3,4,5,1,2,1,1,1])
freq_x = np.bincount(x).argmax()
ind_x = np.where(x == freq_x)[0]

y = np.array([1,1,1,2,3,4,2,4,3,3])
freq_y = np.bincount(x).argmax()
ind_y = np.where(y==freq_y)[0]
print(ind_x)
print(ind_y)

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i.
Sum of all elements
ii.
iii.
Sum of all elements row-wise  
Sum of all elements column-wise

In [35]:

gfg = np.matrix('[4,1,9; 12,3,1;4,5,6]')
tot_sum = gfg.sum()
row_sum = gfg.sum(axis=1)
col_sum = gfg.sum(axis=0)
print(tot_sum)
print(row_sum)
print(col_sum)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find

In [36]:
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])

i.
Sum of diagonal elements

In [37]:
diag_sum = np.trace(n_array)
print(diag_sum)

176


ii. Eigen values of matrix

In [38]:
e_val, e_vec = np.linalg.eig(n_array)
print(e_val,e_vec)

[98.16835147 28.097044   49.73460452] [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


iv. Inverse of matrix

In [40]:
inverse = np.linalg.inv(n_array)
print(inverse)

[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


v. Determinant of matrix

In [41]:
determinant = np.linalg.det(n_array)
print(determinant)

137180.0000000001


(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i.
p = [[1, 2], [2, 3]]

In [42]:
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
product = np.dot(p,q)
cov = np.cov(p.T,q.T)
print(product,cov)


[[16 19]
 [26 31]] [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]



ii.
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]

In [15]:

p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
product2 = np.dot(p,q)
cov2 = np.cov(p.flatten(), q.flatten())
print(product2,cov2)

[[16 19  5]
 [26 31  8]
 [46 55 14]] [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [16]:

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

inner = np.inner(x, y)

outer = np.outer(x.flatten(), y.flatten())

cartesian = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print(inner, outer, cartesian)


[[17 52]
 [13 62]] [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]] [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a)  
For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

In [17]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

i.
Find element-wise absolute value

In [18]:
a_arr = np.abs(array)
print("absolute values : ",a_arr)

absolute values :  [[1 2 3]
 [4 5 6]]


ii.
Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
row.

In [20]:
flat = array.flatten()
p_flat = np.percentile(flat,[25,50,75])
p_col = np.percentile(array,[25,50,75],axis=0)
p_row = np.percentile(array,[25,50,75],axis=1)
print("Percentiles Flattened:", p_flat)
print("Percentiles Col-wise: ", p_col)
print("Percentiles Row-wise : ", p_row)

Percentiles Flattened: [-3.5 -0.5  2.5]
Percentiles Col-wise:  [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles Row-wise :  [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


iii. Mean, Median and Standard Deviation of flattened array, of each column, and
each row

In [22]:

mean_flat = np.mean(flat)
median_flat = np.median(flat)
std_flat = np.std(flat)

mean_col = np.mean(array, axis=0)
median_col = np.median(array, axis=0)
std_col = np.std(array, axis=0)

mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

print("Flattened Mean:", mean_flat, "Median:", median_flat, "Std:", std_flat)
print("Col wise  Mean:", mean_col, "\nMedian:", median_col, "\nStd:", std_col)
print("Row wise  Mean:", mean_row, "\nMedian:", median_row, "\nStd:", std_row)


Flattened Mean: -0.5 Median: -0.5 Std: 3.8622100754188224
Col wise  Mean: [-1.5  1.5 -1.5] 
Median: [-1.5  1.5 -1.5] 
Std: [2.5 3.5 4.5]
Row wise  Mean: [ 0.66666667 -1.66666667] 
Median: [ 1. -4.] 
Std: [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
and truncated value, rounded values

In [23]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

f = np.floor(a)
c = np.ceil(a)
t = np.trunc(a)
r = np.round(a)
print("Floor:", f)
print("Ceiling:", c)
print("Truncated:", t)
print("Rounded:", r)


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling: [-1. -1. -0.  1.  2.  2.  3.]
Truncated: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


Q3: Based on Searching and Sorting

(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find

In [24]:
array = np.array([10,52,62,16,16,54,453])

i.
Sorted array

In [25]:
s_array = np.sort(array)
print("Sorted array:", s_array)


Sorted array: [ 10  16  16  52  54  62 453]


ii. Indices of sorted array

In [26]:
s_indices = np.argsort(array)
print("Indices of sorted array:", s_indices)

Indices of sorted array: [0 3 4 1 5 2 6]


iii. 4 smallest elements

In [27]:
s_4 = np.sort(array)[:4]
print("4 smallest elements:", s_4)


4 smallest elements: [10 16 16 52]


iv. 5 largest elements

In [28]:
l_5 = np.sort(array)[-5:][::-1]
print("5 largest elements:", l_5)


5 largest elements: [453  62  54  52  16]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), **find**

In [29]:
array = np.array([1.0,1.2,2.2,2.0,3.0,2.0])

i.
Integer elements only

In [30]:
int_el = array[array == array.astype(int)]
print("Integer elements only:", int_el)

Integer elements only: [1. 2. 3. 2.]


ii. Float elements only

In [31]:
f_el = array[array != array.astype(int)]
print("Float elements only:", f_el)

Float elements only: [1.2 2.2]


Q4.
(a) Write a function named img_to_array(path) that reads an image from a specified path and
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
images)

In [32]:
import cv2
import numpy as np

def img_to_array(path, output='image_arr.txt'):
    img = cv2.imread(path)

    if img is None:
        raise ValueError("Image not found or path is incorrect.")

    if len(img.shape) == 2 or img.shape[2] == 1:
        print("Grayscale image detected.")
        gray_img = img if len(img.shape) == 2 else cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        np.savetxt(output, gray_img, fmt='%d')
    else:
        print("RGB image detected.")
        # Save each channel separately
        for i, color in enumerate(['B', 'G', 'R']):
            channel = img[:, :, i]
            np.savetxt(f'{color}_{output}', channel, fmt='%d')

    print("Image saved as text file(s).")


(b) Load the saved file into jupyter notebook?

In [33]:
gray = np.loadtxt('image_array.txt', dtype=np.uint8)
print("Grayscale array loaded:\n", gray)

FileNotFoundError: image_array.txt not found.

In [ ]:
b = np.loadtxt('B_image_array.txt', dtype=np.uint8)
g = np.loadtxt('G_image_array.txt', dtype=np.uint8)
r = np.loadtxt('R_image_array.txt', dtype=np.uint8)

# Reconstruct image
reconstructed_img = cv2.merge([b, g, r])
print("RGB array reconstructed.")
